### PR TITLE
Update utility framework with states, default border, background classes, etc.

### PR DESCRIPTION
**Pull request by melaniebmn**
# Summary | Résumé

Next round of changes, including the version update:

- add default border colour class
- add support for styling based on hover and focus classes
- add support for background classes
- improve default link display
- add class for GCDS focus styling

### CODE REVIEW

**Comment by melaniebmn** [comment]
@ethanWallace I added a `focus-styling` class that allows users to use the focus styling that we use for our components. I'm not sure I like the class name `focus-styling` though, it's quite long. Do you have any ideas for a better name?

**Comment by ethanWallace** [comment]
> @ethanWallace I added a `focus-styling` class that allows users to use the focus styling that we use for our components. I'm not sure I like the class name `focus-styling` though, it's quite long. Do you have any ideas for a better name?

Could we name it something like `gcds-focus`?

**Review by ethanWallace — DISMISSED** [review]
LGTM!

I am going to approve this right now, but if we make a decision to switch the focus class name I will do another review.

**Comment by melaniebmn** [comment]
@ethanWallace I updated the focus styling name to `focus:default` to better align with the rest of our state classes. Can you please review it again? Thank you!

**Review by ethanWallace — APPROVED** [review]
LGTM!

**Pull request merged**
